packages:
  - 'smelter'
  - 'smelter-core'
  - 'smelter-node'
  - 'smelter-browser-render'
  - 'smelter-web-wasm'
  - 'examples/node-examples'
  - 'examples/vite-example'
  - 'create-smelter-app'
  - 'create-smelter-app/templates/node-minimal'
  - 'create-smelter-app/templates/node-express-zustand'
